apiVersion: v1
kind: Pod
metadata:
  namespace: ckad
  creationTimestamp: null
  labels:
    run: loop
  name: loop
spec:
  containers:
  - image: busybox
    name: loop
    args: 
    - /bin/sh
    - -c
    - while true; do    currdate=$(date);   echo "current date is $currdate"; done
