apiVersion: v1
kind: Pod
metadata:
  namespace: ckad
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx:1.17.10
    name: nginx
    env: 
    - name: "DB_URL"
      value: "postgresql://mydb:5432"
    - name: "DB_USERNAME"
      value: "admin"
    ports:
    - containerPort: 80
