apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temporary
  name: temporary
  namespace: ckad
spec:
  containers:
  - image: busybox
    name: temporary
    command: [ "sleep", "999999"  ]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
