apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  containers:
  - image: nginx
    name: complex-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
