apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: data-exchange
spec:
  containers:
  - image: arvubd/mybusybox:1.0
    name: main-app
    command: [ "sh" , "/test.sh" ]
    volumeMounts: 
    - mountPath: /var/app/data
      name: cache-dir
  - image: arvubd/mycount
    name: sidecar
    command: [ "sh" , "/count.sh" ]
    volumeMounts: 
    - mountPath: /var/app/data
      name: cache-dir
  volumes: 
  - name: cache-dir
    emptyDir: {}
