apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-ping
spec:
  successfulJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command: [ "curl", "http://www.google.com" ]
          restartPolicy: OnFailure
