apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web-server
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-server
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 30
    ports:
    - containerPort: 80
